# Generated by Django 2.2.7 on 2019-12-01 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Enter a category tag (e.g. search_engine_and_portals, computers_and_technology etc.)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Enter a category name (e.g. Search Engines & Portals, Computers & Technology etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the domain language (e.g. English, French, Japanese etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Enter the domain (e.g. vnexpress.net, facebook.com, google.com, etc.)', max_length=200)),
                ('name', models.CharField(help_text='Enter the domain title (e.g. Vnexpress, Facebook, Google, etc.)', max_length=200)),
                ('rank_alexa_global', models.IntegerField(help_text='Enter the global Alexa rank', null=True)),
                ('rank_alexa_vietnam', models.IntegerField(help_text='Enter the Vietnam Alexa rank', null=True)),
                ('is_foreign', models.BooleanField(help_text='Select if domain is foreign site')),
                ('is_mobile', models.BooleanField(help_text='Select if domain is mobile site')),
                ('is_porn', models.BooleanField(help_text='Select if domain is porn')),
                ('is_malware', models.BooleanField(help_text='Select if domain is malware')),
                ('is_phishing', models.BooleanField(help_text='Select if domain is phishing')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Language')),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Category')),
            ],
        ),
    ]
