# Generated by Django 2.2.7 on 2019-12-01 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='rank_alexa_global',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='rank_alexa_vietnam',
        ),
    ]
