# Generated by Django 2.2.7 on 2019-12-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20191201_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(help_text='Enter the domain (e.g. vnexpress.net, facebook.com, google.com, etc.)', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter the domain language (e.g. English, French, Japanese etc.)', max_length=200, unique=True),
        ),
    ]
