# Generated by Django 2.2.7 on 2019-12-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20191201_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['tag', 'name']},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['domain']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
    ]
